function y = bezier5(aMat, t)

    baseDof = 6;
    y = zeros(size(aMat,1), 1);

    for i = baseDof+1 : size(aMat, 1)

        a0 = aMat(i, 1);
        a1 = aMat(i, 2);
        a2 = aMat(i, 3);
        a3 = aMat(i, 4);
        a4 = aMat(i, 5);
        a5 = aMat(i, 6);

        %%% 6-th order
        % y(i-baseDof) = ...
        %                  a0 *(1-x)^6      + ...
        %               6 *a1 *(1-x)^5 *x   + ...
        %              15 *a2 *(1-x)^4 *x^2 + ...
        %              20 *a3 *(1-x)^3 *x^3 + ...
        %              15 *a4 *(1-x)^2 *x^4 + ...
        %               6 *a5 *(1-x)   *x^5 +  ...
        %                  a6          *x^6;

        %%% 5-th order
        y(i-baseDof) =     a0*(1 - t)^5 + ...
                         5*a1*(1 - t)^4*t + ...
                        10*a2*(1 - t)^3*t^2 + ...
                        10*a3*(1 - t)^2*t^3 + ...
                         5*a4*(1 - t)*  t^4 + ...
                           a5*t^5;
    end

end