function [fitresult, gof, h1] = createFit_b6(tau, q1, titleName, figH)
%CREATEFIT(TAU,Q1)
%  Create a fit to a 6-th order Bezier polynomial.
%
%  Data for 'bezier' fit:
%      X Input : tau
%      Y Output: q1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 09-Sep-2017 01:23:00.


%% Fit: 'bezier'.
[xData, yData] = prepareCurveData( tau, q1 );

% Set up fittype and options.
ft = fittype( 'a0*(1-x)^6 + 6*a1*(1-x)^5 * x +  15*a2*(1-x)^4 * x^2 +  20*a3*(1-x)^3 * x^3 +  15*a4*(1-x)^2 * x^4 +  6*a5*(1-x)*x^5 +  a6* x^6;',...
              'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.957506835434298 0.964888535199277 0.157613081677548 0.970592781760616 0.957166948242946 0.485375648722841 0.8002804688888];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

if figH ~= 0
    
    % Plot fit with data.
    h1 = figure(figH);
    % figure( 'Name', 'bezier' );
    h = plot( fitresult, xData, yData ); hold on;
    legend('off'); % legend( h, 'q1 vs. tau', 'bezier', 'Location', 'NorthEast' );
    plot(xData(end), yData(end), 'X', 'LineWidth',2, 'Color','k');
    % Label axes
    xlabel tau;
    ylabel q1
    grid on
    title(titleName);
    
    h1.WindowStyle = 'docked';  hold on

else
    h1 = [];
end


end