function [fitresult, gof, h1] = createFit_b5(tau, q1, titleName, figH)
%CREATEFIT(TAU,Q1)
%  Create a fit to a 5-th order Bezier polynomial.
%
%  Data for 'bezier' fit:
%      X Input : tau
%      Y Output: q1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 09-Sep-2017 01:23:00.


%% Fit: 'bezier'.
[xData, yData] = prepareCurveData( tau, q1 );

% Set up fittype and options.
ft = fittype( 'a0*(1 - x)^5 + 5*a1*(1 - x)^4*x + 10*a2*(1 - x)^3*x^2 + 10*a3*(1 - x)^2*x^3 + 5*a4*(1 - x)*  x^4 + a5*x^5;',...
              'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.9575068 0.9648885 0.15761 0.97059 0.9572 0.485375];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

if figH ~= 0
    
    % Plot fit with data.
    h1 = figure(figH);
    % figure( 'Name', 'bezier' );
    h = plot( fitresult, xData, yData ); hold on;
    legend('off'); % legend( h, 'q1 vs. tau', 'bezier', 'Location', 'NorthEast' );
    plot(xData(end), yData(end), 'X', 'LineWidth',2, 'Color','k');
    % Label axes
    xlabel tau;
    ylabel q1
    grid on
    title(titleName);
    
    h1.WindowStyle = 'docked';  hold on

else
    h1 = [];
end


end